# Generated by Django 2.2.5 on 2020-06-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(db_column='departmentname', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(db_column='employeeID', primary_key=True, serialize=False)),
                ('employeename', models.CharField(db_column='employeename', max_length=45)),
                ('superioremployeeid', models.IntegerField(blank=True, db_column='superioremployeeID', null=True)),
                ('departmentid', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('month', models.DateField()),
                ('overtimekind', models.CharField(db_column='overtimekind', max_length=45)),
                ('overtimehour', models.IntegerField(db_column='overtimehour')),
                ('departmentid', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Department')),
                ('employeeid', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('month', models.DateField()),
                ('leavekind', models.CharField(db_column='leavekind', max_length=45)),
                ('leavedays', models.IntegerField(db_column='leavedays')),
                ('departmentid', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Department')),
                ('employeeid', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancedate', models.DateField()),
                ('attendancetime', models.TimeField(blank=True, null=True)),
                ('retiredtime', models.TimeField(blank=True, null=True)),
                ('worktime', models.TimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('departmentid', models.ForeignKey(db_column='departmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Department')),
                ('employeeid', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Employee')),
            ],
        ),
    ]
